version: "3.9"
services:
  influxdb2:
    image: influxdb:2.0.6
    ports:
      - "8086:8086"
    network_mode: "bridge"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: super-secret
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: oops_this_is_committed_to_source_control
      DOCKER_INFLUXDB_INIT_ORG: initial-org
      DOCKER_INFLUXDB_INIT_BUCKET: initial-bucket
